name: Deploy Web Application

on:
  push:
    branches:
      - prod
      - dev
      - staging

env:
  common:
    REACT_APP_FIREBASE_API_KEY: ${{ secrets.PROD_FIREBASE_API_KEY }}
    REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.PROD_FIREBASE_AUTH_DOMAIN }}
    REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROD_FIREBASE_PROJECT_ID }}

  prod:
    ENVIRONMENT: prod

  dev:
    ENVIRONMENT: dev

  staging:
    ENVIRONMENT: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: ${{ matrix.env }}
    strategy:
      matrix:
        env:
          - common
          - ${{ github.ref_slug }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync build/ s3://your-bucket-name
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id
          your-cloudfront-distribution-id --paths "/*"
