name: Deploy Web Application

on:
  push:
    branches:
      - prod

env:
  REACT_APP_FIREBASE_API_KEY: ${{ secrets.PROD_FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.PROD_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROD_FIREBASE_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - branch: prod
            environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA5OPECVRC6ZKZ5IMP
          aws-secret-access-key: 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
          aws-region: ap-southeast-1
          # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          # role-duration-seconds: 1200
          # role-session-name: MySessionName
      - name: Deploy to S3
        run: aws s3 sync build/ s3://github-demoapp
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2QFXG8T9OPTCH --paths "/*"
